name: Bug Report
description: Report a reproducible bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: ""
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Briefly describe the bug...
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows
        - macOS
        - Linux
        - Android
        - iOS
        - Other
      default: 0
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: Browser (if applicable)
      description: Which browser are you using? (e.g., Chrome, Firefox, Safari)
      placeholder: e.g. Chrome
    validations:
      required: false
  - type: input
    id: browser-version
    attributes:
      label: Browser Version (if applicable)
      description: What is the version of your browser?
      placeholder: e.g. 100.0.4896.127
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
