name: Documentation
description: Suggest improvements or additions to the documentation
title: '[Docs]: '
labels: ['documentation', 'triage']
assignees: ''
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to improve our documentation!
  - type: input
    id: doc-part
    attributes:
      label: What part of the documentation needs improvement?
      description: A clear and concise description of the section or aspect of the documentation that needs attention.
      placeholder: e.g. The installation guide is outdated.
    validations:
      required: true
  - type: textarea
    id: improvement-description
    attributes:
      label: Describe the improvement you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the documentation improvement here.
    validations:
      required: false
