name: Question
description: Ask a question about the project
title: '[Question]: '
labels: ['question', 'triage']
assignees: ''
body:
  - type: markdown
    attributes:
      value: |
        Thanks for asking a question! We'll do our best to help.
  - type: textarea
    id: question-text
    attributes:
      label: What is your question?
      description: A clear and concise question about the project.
      placeholder: Type your question here...
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Add any additional context that might help answer your question.
    validations:
      required: false
